name: The Hall of Impossible Dreams
description: A collection of fiction and code
meta_description: "The Hall of Impossible Dreams - A collection of fiction and code"

markdown: kramdown
highlighter: rogue
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.hallofdreams.org'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://www.hallofdreams.org'
author:         'David'
